apiVersion: apps/v1
kind: Deployment
metadata:
  name: qtask-broker-deployment
  labels:
    app: qtask-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qtask-broker
  template:
    metadata:
      labels:
        app: qtask-broker
    spec:
      containers:
      - name: qtask-broker-container
        image: cloudcitycolombia/qtask-broker:latest
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: REDIS_HOST
          value: "40.76.248.127"
        - name: REDIS_PORT
          value: "30000"
        - name: REDIS_USERNAME
          value: "default"
        - name: REDIS_PASSWORD
          value: "3n7F8fqEFfzC2vfCaeztlXNKxtcIJjxX2Mht+GadPmyGdXbrI36CHw=="
        - name: NUM_PARTITIONS
          value: "1"
        - name: UVICORN_WORKERS
          value: "1"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      imagePullSecrets:
      - name: dockerhub-secret

---

apiVersion: v1
kind: Service
metadata:
  name: qtask-broker-service
  labels:
    app: qtask-broker
spec:
  type: NodePort
  selector:
    app: qtask-broker
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30001
